language: node_js
node_js:
  - '12'
cache: npm
dist: xenial
sudo: false
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - npm install
script:
  - npm run ci
deploy:
  provider: heroku
  api_key:
    secure: m70lOEMfD4YVWuV5b/mJRBbMvmquUgjihLcrAPBfdIG/BIsE9+qwLM/ClpvVLBR5w0OrKI+/E+PRI6AwMfczLrXbAM82n7U/cI5E2++lCBBBAF5tDQR9Imxx068i0qHujI5wxuBkgJrJ+4MJfIurl8KtHGSSwdurFomjgTfmToY/KOjtPyNVyuz5FQ8/kkqDjhgs9zxtHWsI9H42mxdRBE1YMY/t+zdMCXv3++QSzaW3ZGeBrAqptCQeJ2UyLE2O7+IaicPF7P+QdKYxMu8W5WUytQk+qnPMlUNOPdheklrP/0H6+VQBBsQcgcRvx9zGgXIBDLoklD7XWuF4BFH9fxpgQ0eVCfYr4Oc6q+Fzuhmks2cZ+x2wGbJEas5biqVxWxFOx7FLz0eq2a/dJgb9keT86PBg5TcFzBXXZXSgDRe0yqXnLTela9jWKMpEPfNg8WehEm9EJQUWeO3J4+IY+uq5QnBDdqUDqJzSVFoiyB1hkrYN3j0huDuDqfVNrSb9PyF02WGggXqskI7JNFj6vnlcCcmk6iD0XN6C5wL+++vRsZ57FbCestA7lRJjXbd4jZsYFpF3dNmue06p5ZdlPn4/jm1djt1DK5dBm2B1Ur3J6l3+ocSlN2IXKCJUJxxQ9cTacaGg5rlh10JHPqEbB5w6qs3BUaad9ITkKkqgBgU=
  app: conorsgapminder
  # on: 
  #   branch: master
